### ISSUE TITLE
Max range 4kHz

### ISSUE THREAD

**Issue by orbisvicis** [woheller69/audio-analyzer-for-android#10]
I'm looking for a spectrogram that can analyze lower-ultrasonic frequencies. I'm curious to know why the max range of this app is 4kHz.

**Comment by woheller69** [comment]
simply increase the sample rate

That is a consequence of https://en.m.wikipedia.org/wiki/Nyquist%E2%80%93Shannon_sampling_theorem

**Comment by matj1** [comment]
Usual audio sampling rate is over 44 kHz. So, according to Shannon sampling theorem, It should analyze frequencies up to 22 kHz. Does this app downsample the input to 8 kHz? If so, why?
