### ISSUE TITLE
[Question/Feature request] Sampling/EQ weighting to remove background noise

### ISSUE THREAD

**Issue by Sophira** [woheller69/audio-analyzer-for-android#11]
Hi there,

First of all, I *love* this app. Thank you so much for your work on it!

Is there any way to be able to leave the phone alone, let it record background noise, and then have the app EQ the recorded background noise (perhaps with options for average/max values) out of the analysed sound?

I can see a "Load Calibration" menu option which I'm guessing could probably be used for this (even if that's not its intended purpose), but while the file format looks simple enough, it'd be nice to be able to do this within the app itself, especially if you don't want to overwrite a calibration you've already loaded. (And it'd explicitly not be for calibration purposes anyway since it would be location-dependent.)

Hopefully I'm making sense here!

**Comment by woheller69** [comment]
sounds like a good idea for an enhancement. But I don't know if I will find the time and if I am expert enough to do that.
I am maintaining this app because the original author did not work on it anymore and I did not want to let it die...

**Comment by woheller69** [comment]
The code is quite complex. I think the risk is too high that something breaks when adding this feature
