### ISSUE TITLE
[suggestion] Releasing the apk here on Github

### ISSUE THREAD

**Issue by EdoSecco** [woheller69/audio-analyzer-for-android#12]
I use [Obtainium](https://github.com/ImranR98/Obtainium) and it would be great if you publish the apk in the release section.

Thank you!

**Comment by woheller69** [comment]
You can upgrade from F-Droid via Obtainium

**Comment by RustoMCSpit** [comment]
> You can upgrade from F-Droid via Obtainium

fdroid is insecure, please watch side of burritos videos on it. it's why we all use obtainium
