### ISSUE TITLE
android custom icon theming support

### ISSUE THREAD

**Issue by RustoMCSpit** [woheller69/audio-analyzer-for-android#13]

**Comment by woheller69** [comment]
[audioSpectrumAnalyzer-release.apk.zip](https://github.com/woheller69/audio-analyzer-for-android/files/11998349/audioSpectrumAnalyzer-release.apk.zip)

**Comment by RustoMCSpit** [comment]
> [audioSpectrumAnalyzer-release.apk.zip](https://github.com/woheller69/audio-analyzer-for-android/files/11998349/audioSpectrumAnalyzer-release.apk.zip)

? could you put the .apk in the files section so obtainium can see it
