### ISSUE TITLE
Stream external microphone data directly

### ISSUE THREAD

**Issue by fhaefele** [woheller69/audio-analyzer-for-android#17]
I have a Patterson M500-384 ultrasound microphone that I connect to my Google Pixel 7 running Android 13 and the latest released version of "Audio Analyzer for Android" downloaded with F-Droid.
https://batsound.com/product/m500-384-usb-ultrasound-microphone/

I thought I can also use the USB audio stream as input, but I see no option of doing so. It seems that the ADC in the phone itself is sampling the incoming audio stream again at the highest sampling rate of 192k which is obviously lower than the intended 384k. Do you know how I could stream the microphone data directly into the app?

**Comment by atikattar1104** [comment]
The App Also Doesn't Support Bluetooth Microphones. Like From TWS Earbuds, Etc.
