### ISSUE TITLE
rotating tablet stops recording

### ISSUE THREAD

**Issue by sunhasgothishaton** [woheller69/audio-analyzer-for-android#18]
I'm running version 2.4 from fdroid, on a Samsung a7 lite tablet runnung android 12.

When I record then rotate the tablet, it reports recording is saved and keeps on recording. To stop recording, I have to press the "rec" button twice to stop.

I get two .wav files. The first records upto me rotating my tablet. The second is always 8k and doesn't contain any recording.

Can you help?

**Comment by woheller69** [comment]
This should fix it.

-Uninstall
-Remove .zip and install

[audioSpectrumAnalyzer-release.apk.zip](https://github.com/woheller69/audio-analyzer-for-android/files/12734791/audioSpectrumAnalyzer-release.apk.zip)

**Comment by sunhasgothishaton** [comment]
Yes, it works now, great.

Thank you.
