### ISSUE TITLE
Please tell me which formula is used in this paragraph

### ISSUE THREAD

**Issue by Pannarrow** [woheller69/audio-analyzer-for-android#20]
This code is in "STFT.java"， "spectrumAmpOutDB[i] = 10.0 * log10(spectrumAmpOut[i]);". I found the dbfs formula "20.0 * log10(sample/65535)", Why do we use 10.0

**Comment by woheller69** [comment]
Good point, I have not written that part of the code.
Maybe @bewantbe can explain?

**Comment by woheller69** [comment]
As far as I understand, the code is calculating the power spectrum (squared magnitudes of complex amplitudes).

Therefore the factor of 10 used in the line:

spectrumAmpOutDB[i] = 10.0 * log10(spectrumAmpOut[i]);

is appropriate. This line converts the power spectrum values to decibels. 
The factor of 10 is commonly used when calculating decibels for power, and it aligns with the standard practice in audio signal processing.

**Comment by Pannarrow** [comment]
Don't we end up with dbfs?

**Comment by Pannarrow** [comment]
Don't we end up with dbfs?

**Comment by Pannarrow** [comment]
thank you very match！

**Comment by bewantbe** [comment]
Apologize for the late response.

> 
> spectrumAmpOutDB[i] = 10.0 * log10(spectrumAmpOut[i]);
> 

The code here is calculating DB of the amplitude (`Amp`) of the "spectrum". The power spectrum, or more precisely [Spectral density](https://en.wikipedia.org/wiki/Spectral_density), is already the square of the wave amplitude, this calculation can be seem in function [`fftToAmp`](https://github.com/bewantbe/audio-analyzer-for-android/blob/6cc84dc789811cd3d39aaebe2635a367b7eceacf/audioSpectrumAnalyzer/src/main/java/github/bewantbe/audio_analyzer_for_android/STFT.java#L304C18-L304C27).

**Comment by Pannarrow** [comment]
> 对于迟到的回复，我们深表歉意。
> 
> > spectrumAmpOutDB[i] = 10.0 * log10（spectrumAmpOut[i]）;
> 
> 这里的代码是计算“频谱”振幅（）的DB。功率谱，或者更准确地说是[光谱密度](https://en.wikipedia.org/wiki/Spectral_density)，已经是波幅的平方，这个计算似乎是函数[](https://github.com/bewantbe/audio-analyzer-for-android/blob/6cc84dc789811cd3d39aaebe2635a367b7eceacf/audioSpectrumAnalyzer/src/main/java/github/bewantbe/audio_analyzer_for_android/STFT.java#L304C18-L304C27)。`Amp`

Why do I get dbfs less than -96

**Comment by bewantbe** [comment]
> Why do I get dbfs less than -96

The overall "DBFS" should not less that -96dB in general, although specially crafted data could break it, e.g. RMS([1, -1, 1, -1, ...]/2^16) = -96.33dB; RMS([1, 0, -1, 0, ...]/2^16) = -99.3dB).

In your case, I believe you are referring to DBFS in the spectrum. The level of the spectrum can be lower than -96dB because -96dB only limits the __sum__ of the energy across all frequencies in the spectrum.

Say, FFT length is 1024, then for -96dB white noise, the spectrum level should be around -96dB + 10*log10(1/1024) = -126 dB.
