### ISSUE TITLE
Problems with zooming / cursor frequency

### ISSUE THREAD

**Issue by RalphMOekoFor** [woheller69/audio-analyzer-for-android#22]
Hello,

I'm reaching out with an inquiry regarding the Audio Spectrum Analyzer, which I've generally found to be an excellent tool. However, I'm encountering a persistent issue. Once I set the cursor frequency, I seem to lose the ability to zoom into the spectrograms. Any attempt to zoom in only results in the cursor frequency adjusting to where my fingers are placed.

This problem doesn't resolve with any of the settings I've tried adjusting, and it persists even after closing and reopening the app. Currently, the only solution appears to be reinstalling the app, which is far from ideal.

Could you advise whether I'm overlooking a feature or setting that might resolve this issue? Or, is this an identified bug in the app?

Thank you for your assistance.

Best regards,
Ralph

**Comment by woheller69** [comment]
I cannot reproduce. When I set the cursor I can still zoom and the cursor does not change...

**Comment by RalphMOekoFor** [comment]
Strange. Whenever I touch the screen, the cursor frequency is newly set. Might there be any setting, which has effect on this behaviour?

**Comment by woheller69** [comment]
Did you install from F-Droid?

**Comment by RalphMOekoFor** [comment]
Yes, I did.

**Comment by woheller69** [comment]
For zooming you need to place 2 fingers simultaneously and then move

**Comment by RalphMOekoFor** [comment]
Yes, I know... however impossible to zoom and not just adjust the cursor frequency

**Comment by woheller69** [comment]
Tried with several devices, none has this behaviour. What is your device, OS, Android version?

**Comment by RalphMOekoFor** [comment]
Android Version 12, Samsung S10

**Comment by RalphMOekoFor** [comment]
Just tried it on a A7 Lite Tablet with Android 13 - there it works as it should.

Furthermore tried again to fix the bug by reinstall it. Even this didn't help

**Comment by woheller69** [comment]
If after reinstall it behaves different than after first installation, there is something wrong with the device...
