### ISSUE TITLE
Hold peaks

### ISSUE THREAD

**Issue by roninspin** [woheller69/audio-analyzer-for-android#24]
Please, add the option to disable peak fading.

**Comment by woheller69** [comment]
You can try this apk.
[audioSpectrumAnalyzer-release.apk.zip](https://github.com/user-attachments/files/17235665/audioSpectrumAnalyzer-release.apk.zip)

-Uninstall
-Remove .zip and install

It allows adjusting the peak hold time between 0 and 120s

**Comment by roninspin** [comment]
@woheller69, thank you. It works, but 120s is still too little for my needs. I need to disable it completely.

**Comment by woheller69** [comment]
[audioSpectrumAnalyzer-release.apk.zip](https://github.com/user-attachments/files/17239169/audioSpectrumAnalyzer-release.apk.zip)
OK, try this and set the Peak decay rate to 0

**Comment by roninspin** [comment]
Yes, that's what I needed. Thanks!
