### ISSUE TITLE
Document how the "load calibration" menu function works and how to use it

### ISSUE THREAD

**Issue by lucasteinke** [woheller69/audio-analyzer-for-android#6]
Hi, thanks for creating this cool application and making it FOSS.

I assume the function ⋮ → _Load calibration_ is for loading a sine wave to calibrate the microphone to the frequencies which can then be displayed?

How do I generate such a sine wave? How should the file look like?

**Comment by woheller69** [comment]
As far as I know these are provided by some manufacturers, e.g. Dayton

see code
https://github.com/woheller69/audio-analyzer-for-android/commit/faab21915927da8495640a72de0674d92d45f66a

I have not written it, but as far as I understand the code there should be a text file which in every line specifies
a frequency and the amplitude in dB separated by a tab

**Comment by woheller69** [comment]
Here is an example:
[example_calibration.txt](https://github.com/woheller69/audio-analyzer-for-android/files/9778363/example_calibration.txt)
