### ISSUE TITLE
Feature request: screenshot button

### ISSUE THREAD

**Issue by lucasteinke** [woheller69/audio-analyzer-for-android#7]
If I press the side buttons on my Android to create a screenshot, this will generate noise visible in the spectrogram.

Maybe there can be a small camera or "save" icon somewhere to save the current display?

**Comment by woheller69** [comment]
Good point :-)

Please try. Uninstall previous version first. 
Remove .zip from filename
Install

[audioSpectrumAnalyzer-release.apk.zip](https://github.com/woheller69/audio-analyzer-for-android/files/9776711/audioSpectrumAnalyzer-release.apk.zip)

**Comment by woheller69** [comment]
Have you tried it?
