### ISSUE TITLE
FFT Window Length and Time Window overlap

### ISSUE THREAD

**Issue by RalphMOekoFor** [woheller69/audio-analyzer-for-android#8]
Hi!
First of all, a big thank you for developing this app. In fact, it has all the funtions I've been looking for for years.

Nevertheless, I would like to ask if it would be possible to extend two functions:
1. FFT Window Length: there are currently settings of 512 - 32768 possible. Would it be possible to add 128-256 (or even 64)? When analysing recordings of birds, these settings are often essential to be able to recognize details. 
2. Time window overlap: Currently there are settings from 0-87.5%. Would even higher values be possible here? This feature is not as relevant as the first point, though.

Thanks again for the great app!
Best wishes,
Ralph

**Comment by woheller69** [comment]
A great app for recognizing birds is Bird-net 

https://play.google.com/store/apps/details?id=de.tu_chemnitz.mi.kahst.birdnet&gl=US

Maybe you know it already.

I added 64-256 as FFT len and 93,75% for overlap.

Please try and let me know if it works as expected.
Uninstall old app. Remove .zip and install.

[audioSpectrumAnalyzer-release.apk.zip](https://github.com/woheller69/audio-analyzer-for-android/files/9890156/audioSpectrumAnalyzer-release.apk.zip)

**Comment by LR234234** [comment]
It works perfectly, thanks!

I know BirdNET as I help to improve it ;-) However, so far, it is more reliable to listen to the bird yourself or check the spectrogram.

Just another suggestion: would it be possible to add something like a full frame mode? In horizontal Smartphone View, quite a lot space is lost by the headline and also by the 'running numbers (RMS:db Cur: Peak:)' on the left lower side. Maybe, in a full frame view, the upper line is invisible (as the 'running numbers') and the settings for kHz, window length etc. are in the same line as the green buttoms below? The spectrogram would be much better visible.

And a last point: is it possible to add the function to change the window length for sounds which are already recorded? I guess the audio would have to be stored in a temporary cache?

All the best and thanks again for the changes yesterday!
Ralph

**Comment by woheller69** [comment]
what do you mean with "window length for sounds which are already recorded"?

**Comment by LR234234** [comment]
Sorry, that was tricky to understand. What I mean is the following: The App displays the spectrogram of an audio. Then I press the 'Stop' button. If I change the FFT len now, nothing changes in the shown spectrogram. To show the difference, I have to re-record the audio with the reset FFT len (but if the input is a live signal, re-recording is not possible).
Would it therefore be possible that the changes in the FFT len have a direct effect on the Spectrogram that is already displayed? 

Translated with www.DeepL.com/Translator (free version)

**Comment by woheller69** [comment]
I don't think that is possible.
I am not the original author of this app. I am just maintaining it because the author stopped doing it...
As far as I understand the code the stream has already been replaced with the next batch of data at this point.
It would probably also break averaging.

**Comment by LR234234** [comment]
Ok, no problem! But do you think, something like the full frame view is possible?

**Comment by woheller69** [comment]
Try this. It is almost full screen. I added a button next to the screenshot button which you can toggle. Then all the stuff at the bottom is made invisible until you toggle back.

[audioSpectrumAnalyzer-release.apk.zip](https://github.com/woheller69/audio-analyzer-for-android/files/9893973/audioSpectrumAnalyzer-release.apk.zip)

**Comment by RalphMOekoFor** [comment]
Perfect! Thank you very much :-)

**Comment by woheller69** [comment]
-> V2.1, just published.
I also reduced the height of the action bar, so there is even more space for the spectrogram
