### ISSUE TITLE
Add output monitor

### ISSUE THREAD

**Issue by PearKing05** [woheller69/audio-analyzer-for-android#9]
This isn't so much as an issue as it is a feature request, but I feel it would be nice to monitor audio output as well as input.

**Comment by PearKing05** [comment]
It appears that you can use the visualizer class (I'm not good with JavaScript or it's vocabulary) to pick up on output audio but it says that the audio quality may be reduced

**Comment by PearKing05** [comment]
As a follow up I found the class specifically is:
android.media.audiofx.Visualizer

**Comment by woheller69** [comment]
I think the way should be to use MediaRecorder.AudioSource.REMOTE_SUBMIX.

But Google does not want us to capture phone calls, therfore:
CAPTURE_AUDIO_OUTPUT has android:protectionLevel="signature|privileged", so it can only be held by apps that are installed on the system partition or are signed by the platform signing key.

**Comment by woheller69** [comment]
use a cable and connect output to input ?

**Comment by flleeppyy** [comment]
Any updates on this being possible? I really don't want to use some janky audio setup just to visualize system audio.

**Comment by woheller69** [comment]
nothing new. Google does not want us to capture audio output

**Comment by flleeppyy** [comment]
Doesn't make sense though, Wavelet is a thing that takes in system audio, and that's allowed on the app store. so i don't see why this app cant.

**Comment by woheller69** [comment]
Isn't that an equalizer? It does not need to capture audio then
